# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAPNjTrw4iYwEpuwLGcUOPaqcvDpKxux
"""

pip install transformers

pip install torch

pip install sentencepiece

from transformers import T5ForConditionalGeneration, T5Tokenizer

# Load pre-trained T5 tokenizer and model
model = T5ForConditionalGeneration.from_pretrained("t5-small")
tokenizer = T5Tokenizer.from_pretrained("t5-small")

# Long input text
input_text = """
The Indian Space Research Organisation (ISRO) launched a new satellite to monitor weather patterns. This development is part of a broader initiative to improve disaster management
"""

# Preprocess the input text for T5 model
preprocessed_text = "summarize: " + input_text.strip().replace("\n", " ")

# Tokenize and encode into tensor
input_ids = tokenizer.encode(preprocessed_text, return_tensors="pt", max_length=512, truncation=True)

# Generate summary
summary_ids = model.generate(input_ids, max_length=100, min_length=30, length_penalty=2.0, num_beams=4, early_stopping=True)

# Decode summary
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Original Text:\n", input_text)
print("\nGenerated Summary:\n", summary)

from transformers import BartTokenizer, BartForConditionalGeneration

# Load model and tokenizer
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')

# Input text
input_text = """
The Indian Space Research Organisation (ISRO) launched a new satellite to monitor weather patterns.
This development is part of a broader initiative to improve disaster management.
"""

# Encode the input
inputs = tokenizer.encode(input_text, return_tensors='pt', max_length=1024, truncation=True)

# Generate summary
summary_ids = model.generate(inputs, max_length=50, min_length=10, length_penalty=2.0, num_beams=4, early_stopping=True)

# Decode and print
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print("Original Text:\n", input_text)
print("\nGenerated Summary:\n", summary)